added initializer which returns definitly count of domains
internetee/registry pull request #1969
Opened 2021-05-07 14:20 UTC by OlegPhenomenon

Close #[https://github.com/internetee/registrant_center/issues/54](url)

2021-05-10 09:37 UTC, OlegPhenomenon commented
Related to -> https://github.com/internetee/registrant_center/issues/54

2021-05-10 09:42 UTC, yulgolem requested changes
In Rails way "initializer" is a config file for some external lib/gem/service put into `/config/initializers` folder, so I'd ask to consider renaming the PR and entities.

BTW why shouldn't we call method just something like 'init_count_*'?

2021-05-10 09:42 UTC, yulgolem commented on app/controllers/api/v1/registrant/domains_controller.rb
> +        def initialization_count_of__direct_domains
Double underscore?

2021-05-10 09:42 UTC, yulgolem commented on app/controllers/api/v1/registrant/domains_controller.rb
> +        def initialization_count_of__domains
Here as well

2021-05-19 14:30 UTC, yulgolem approved these changes

2021-05-19 14:31 UTC, merged