fix bind_invoice method
internetee/registry pull request #2075
Opened 2021-07-07 06:56 UTC by DinSmol

see issue #1788

2021-07-07 07:50 UTC, yulgolem commented on app/models/bank_transaction.rb
>      errors.add(:base, I18n.t('invoice_was_not_found')) unless invoice
Let's consider to move this check also to` #validate_invoice_data(invoice)` method.

2021-07-07 15:24 UTC, yulgolem approved these changes

2021-07-08 05:52 UTC, yulgolem requested changes
Let's add some tests to be sure.

2021-07-08 06:30 UTC, yulgolem approved these changes

2021-07-08 13:53 UTC, vohmar commented
might be different issue, but maybe its and easy fix to do right here. the method paid error is indeed gone, but if a user creates a valid bank transaction that matches an unpaid invoice error is returned on pressing "bind manually"

undefined method `settings' for nil:NilClass

2021-07-14 11:13 UTC, yulgolem requested changes

2021-07-14 11:13 UTC, yulgolem commented on app/models/bank_transaction.rb
> +    return unless registrar.present? && registrar.settings['balance_auto_reload']
Looks like we do not have this covered in tests, are we?

2021-07-14 12:50 UTC, yulgolem commented
I'd suggest to move a bind manually error `undefined method `settings' for nil:NilClass` to separate issue and complete/close this one - you know, just to eat the elephant one bite a time.

2021-07-15 05:58 UTC, yulgolem approved these changes

2021-07-15 05:59 UTC, merged