added dnskey update prohibited status
internetee/registry pull request #2153
Opened 2021-09-07 09:23 UTC by OlegPhenomenon

Close #2143

2021-09-07 11:21 UTC, yulgolem approved these changes

2021-09-09 10:06 UTC, vohmar commented
objUpdateProhibited
* epp error message: <result code="2400"><msg lang="en"/>
* adding new nameserver and contact objects to the domain succeeded: https://st-adm.infra.tld.ee/admin/epp_logs/46939
* removing existing nameserver and contact objects was successful: https://st-adm.infra.tld.ee/admin/epp_logs/46963
* registrant change was successful: https://st-adm.infra.tld.ee/admin/epp_logs/47027

so the only operation that failed was changing ip addresses of existing nameserver records. Adding new dnssec key was successful as expected

extensionUpdateProhibited

seems to work as expected
changing ns ip successful, dnssec key removal, adding and change was denied

2021-09-10 07:02 UTC, vohmar commented
serverObjUpdateProhibited - spotted issues:

* on adding ipv6 address to an existing ns record this error was returned:  <result code="2304"><msg lang="en">Object status prohibits operation :serverDnskeyUpdateEnabled</msg> - there is no such status, the message should reference serverObjUpdateProhibited in this scenario (https://st-adm.infra.tld.ee/admin/epp_logs/47423). 
  * same error message on adding new ns record, removing ns record, registrant change
  
* in admin where new statuses can be set on an object the new statuses are listed in a complete form while other statuses have server prefix omitted  as one can only set server prefixed statuses in admin. Please do the same for the new statuses

2021-09-10 12:31 UTC, yulgolem approved these changes

2021-09-10 12:32 UTC, yulgolem commented on app/models/feature.rb
> +    return false if ENV['obj_and_extensions_prohibited'] == 'false'
Empty line here

2021-09-10 12:32 UTC, yulgolem commented on app/models/feature.rb
> +end
And here

2021-09-10 12:35 UTC, yulgolem requested changes
Let's add some high-level tests for the feature-toggle.
Like 'key is absent or set to false - feature not active, key. is present and set to true - feature is active'

2021-09-10 13:29 UTC, yulgolem approved these changes

2021-09-14 09:35 UTC, merged