added new task and test for replace new status for locked domains
internetee/registry pull request #2163
Opened 2021-09-20 12:18 UTC by OlegPhenomenon

2021-09-20 12:49 UTC, yulgolem requested changes

2021-09-20 12:49 UTC, yulgolem commented on app/jobs/replace_upd_to_obj_upd_prohibited_job.rb
> +  def perform(mode, rollback = false)
Consider using keyword arguments when argument's count is more than one.

2021-09-20 12:49 UTC, yulgolem commented on app/jobs/replace_upd_to_obj_upd_prohibited_job.rb
> +    start_adding_new_status_for_locked_domains(mode, rollback)
Same here.

2021-09-20 12:49 UTC, yulgolem commented on app/jobs/replace_upd_to_obj_upd_prohibited_job.rb
> +          if rollback
Try to avoid nested conditions.

2021-09-20 12:49 UTC, yulgolem commented on lib/tasks/replace_upd_to_obj_upd_prohibited.rake
> +      ReplaceUpdToObjUpdProhibitedJob.perform_later('add')
Consider using symbols instead of strings as arguments, preferably like `perform_later(action: :add)` or `(action: :remove)`

2021-09-20 13:34 UTC, yulgolem approved these changes

2021-09-20 13:34 UTC, yulgolem commented on app/jobs/replace_upd_to_obj_upd_prohibited_job.rb
> +    if action == :add and !domain.statuses.include? 'serverUpdateProhibited'
We are not tweaking execution flow here, so it's better to use `&&` instead of `and`

2021-09-20 13:34 UTC, yulgolem commented on app/jobs/replace_upd_to_obj_upd_prohibited_job.rb
> +        if domain.locked_by_registrant? && rollback
Consider moving this block to private method which gets `domain` as an argument - thus we'll lower the overall complexity

2021-09-20 14:05 UTC, yulgolem approved these changes

2021-09-20 14:10 UTC, OlegPhenomenon commented
Instruction:

1. First, you need to release new circuits into production.
2. Then we start the task `rake locked_domains:add_new_status` and wait for the task to complete
3. Then we roll out new functionality for blocking the domain into production
4. Then we start the task `rake locked_domains:remove_old_status` and when the task is completed

2021-09-20 14:12 UTC, OlegPhenomenon commented
If something went wrong, then the instructions on how to roll back:
First you need to disable the new functionality by adding `obj_and_extensions_prohibited: 'false'` in `application.yml`
Then we perform this task `rake locked_domains:rollback_remove_old_status` and wait for it to complete
Then we perform this task `rake locked_domains:rollback_add_new_status` and wait for it to complete

2021-09-21 09:18 UTC, OlegPhenomenon commented
**Test assignment**

Task launch:
application.yml:
obj_and_extensions_prohibited: 'true' - this line must either be uncommented and have the value 'true'

We start tasks:
`rake locked_domains: add_new_status`

Expected Result: All locked domains that have the following statuses 
``` 
DomainStatus :: SERVER_UPDATE_PROHIBITED, 
DomainStatus :: SERVER_DELETE_PROHIBITED, 
DomainStatus :: SERVER_TRANSFER_PROHIBITED`` 
should add the following status:
``` DomainStatus :: SERVER_OBJ_UPDATE_PROHIBITED```

After the task has completed, run the following task:
`rake locked_domains: remove_old_status`

This task should remove the `DomainStatus :: SERVER_UPDATE_PROHIBITED` status from all domains that have a domain locked status by the registrant.

Expected task, blocked domain should have at least the following statuses:
```
DomainStatus :: SERVER_OBJ_UPDATE_PROHIBITED,
DomainStatus :: SERVER_DELETE_PROHIBITED,
DomainStatus :: SERVER_TRANSFER_PROHIBITED
```

a view should be displayed in the console with something like the following content:
```
"Proccesing #{count} domains of #{Domain.count}"
```

As a result, the following file `log/replace_upd_to_obj_upd_prohibited.log` should appear in the log directory with approximately the following content:

```
I, [2010-07-04T21:00:00.000000 #149]  INFO -- : Ran ReplaceUpdToObjUpdProhibitedJob!
I, [2010-07-04T21:00:00.000000 #149]  INFO -- : Proccesing 6 domains of 6
I, [2010-07-04T21:00:00.000000 #149]  INFO -- : Successfully proccesed 6 domains of 6
```

2021-09-22 10:01 UTC, OlegPhenomenon commented
# INSTRUCTIONS:
# The task works as follows, it finds a domain that has a domain lock mark and replaces the status serverUpdateProhibited with serverObjUpdateProhibited
# For run this task it need to type `rake locked_domains:replace_new_status`
# Whole results will saved into log/replace_upd_to_obj_upd_prohibited.log
# It need to make sure before launching that these statuses mean that the domain has a domain lock, otherwise this scanner will not find the required domains.
# Therefore, it is better that the value `enable_lock_domain_with_new_statuses` in the `application.yml` file is commented out or has the status false before starting. After the task has been completed, set the value `enable_lock_domain_with_new_statuses` to true, and then the domain with the following statuses `serverDeleteProhibited, serverTransferProhibited, serverObjUpdateProhibite` will be considered blocked now.

# If for some reason it need to roll back the result, then this value `enable_lock_domain_with_new_statuses` must be true, and run the command `rake locked_domains:rollback_replacement_new_status`

2021-09-23 14:12 UTC, merged