Poll message contact missing code
internetee/registry pull request #2312
Opened 2022-03-15 07:58 UTC by thiagoyoussef

2022-03-15 12:01 UTC, OlegPhenomenon requested changes

2022-03-15 12:01 UTC, OlegPhenomenon commented on test/models/registrant_user/registrant_user_creation_test.rb
> +    )
please put instead hardcoded values as "john-001 or Acme and other" the variables of object like "contact.code" "registrant_user" and so on

2022-03-16 08:59 UTC, OlegPhenomenon approved these changes

2022-03-17 17:19 UTC, vohmar commented
poll message when registrant name was automatically changed according to business registry data:
<msg>Contact update: 253533 name updated from Kaader kuus OÜ to OÜ Kaader 6 by the registry</msg>
https://st-adm.infra.tld.ee/admin/epp_logs/54089
correct contact code in case is BEST:KAADER6

poll message when registrant name was automatically changes according to eid data:
<msg>Contact EEDIRECT:KATKI1 has been updated by registrant</msg>
https://st-adm.infra.tld.ee/admin/epp_logs/54085

2022-03-29 08:47 UTC, closed without merging