Fix check force delete lift bug
internetee/registry pull request #2418
Opened 2022-08-14 16:20 UTC by thiagoyoussef

close #2413

2022-08-16 07:31 UTC, OlegPhenomenon approved these changes

2022-08-16 07:33 UTC, OlegPhenomenon requested changes

2022-08-16 07:33 UTC, OlegPhenomenon commented on lib/tasks/check_force_delete.rake
> +    validation.validation_eventable.need_to_start_force_delete?
where did you hide the check for need_to_lift_force_delete? how will he understand that force delete can be removed on a specific domain?

2022-09-15 09:12 UTC, OlegPhenomenon requested changes

2022-09-15 09:12 UTC, OlegPhenomenon commented on app/models/validation_event.rb
> +
I think that is a bad idea.

The last time we put checks for force delete and lift force delete into callbacks, firstly there were performance issues, and secondly, unexpected behavior happened when lift force delete worked in a situation where it was not supposed to.

In addition, there is an opinion that using callback is not a good practice in terms of support, code testing. But that's just an opinion, everyone has their own opinion :)

2022-10-10 13:29 UTC, OlegPhenomenon approved these changes

2022-10-11 13:28 UTC, vohmar commented
an issue detected - if user has the same invalid email with multiple contact objects related to a single domain registration the amount of false validation_event records is unlimited (seemingly) instead of three records. This is not a rare case in production

2022-10-12 10:54 UTC, merged